### ISSUE TITLE
When installing new instances, provide a link to the admin interface

### ISSUE THREAD

**Issue by vmalloc** [platzio/frontend#23]
When installing a new instance this is what you get:
![Screen Shot 2022-09-15 at 9 05 23](https://user-images.githubusercontent.com/28710/190327110-e3916eb0-ea5e-4f60-a38e-5cae0b4f4a9c.png)

It would be useful to get a link to the admin page from this view

**Comment by popen2** [comment]
This was fixed in https://github.com/platzio/frontend/commit/4c09806fad2147575d5bc1bfdb5d34430b64ce05 (in v0.4.7-beta.4)
