### ISSUE TITLE
Uncaught syntaxError raised when opening deployment-edit form

### ISSUE THREAD

**Issue by ayalash** [platzio/frontend#43]
Error in browser's console:
   ```
Pattern attribute value ^[-a-z0-9]+$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^[-a-z0-9]+$/v: Invalid character in character class
   ```
   
   The error is raised from the pattern of `DeploymentForm`: https://github.com/platzio/frontend/blob/main/src/pages/main/env/deployments/DeploymentForm.vue#L10
   ```
   <div class="mb-3 form-floating" v-if="canHaveName">
        <input
            type="name"
            class="form-control"
            id="name"
            aria-describedby="nameHelp"
            v-model="new_data.name"
            required
            pattern="^[-a-z0-9]+$"
            :maxlength="maxNameLength"
            :disabled="working"
        />
        <label for="name" class="form-label"> Deployment Name </label>
        <div id="nameHelp" class="form-text" v-if="new_data.name">
            <FaIcon icon="keyboard" class="ms-1" fixed-width />
            Enter a valid DNS name,
            {{ maxNameLength - new_data.name.length }} characters left
        </div>
    </div>
    ```

**Comment by ayalash** [comment]
IMO, there are two problems with this error:
1. The `pattern` is very strict, many deployments might have additional characters (for example `-`).
1. The error is displayed as `Uncaught syntaxError` in the console, but is not displayed in the form itself and doesn't forbid the user from setting the name to "illegal" name.

**Comment by pyros82** [comment]
Looking at 
https://github.com/GoogleChrome/chromium-dashboard/issues/3106

Seems like we just need to add a \ before the first -

**Comment by ayalash** [comment]
Thanks @pyros82 !
